-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 17:57:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IDCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`IDCliente`),
  UNIQUE INDEX `IDCliente_UNIQUE` (`IDCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `IDEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Puesto` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`IDEmpleado`),
  UNIQUE INDEX `IDEmpleado_UNIQUE` (`IDEmpleado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `IDProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`IDProducto`),
  UNIQUE INDEX `IDProducto_UNIQUE` (`IDProducto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `Producto_IDProducto` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Existencia` INT NOT NULL,
  `Empleado_IDEmpleado` INT NOT NULL,
  PRIMARY KEY (`Producto_IDProducto`, `Empleado_IDEmpleado`),
  INDEX `fk_Inventario_Producto1_idx` (`Producto_IDProducto` ASC),
  INDEX `fk_Inventario_Empleado1_idx` (`Empleado_IDEmpleado` ASC),
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto_IDProducto`)
    REFERENCES `mydb`.`Producto` (`IDProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Empleado1`
    FOREIGN KEY (`Empleado_IDEmpleado`)
    REFERENCES `mydb`.`Empleado` (`IDEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Empleado` (
  `Empleado_IDEmpleado` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Empleado_IDEmpleado`),
  INDEX `fk_Tipo_Empleado_Empleado_idx` (`Empleado_IDEmpleado` ASC),
  CONSTRAINT `fk_Tipo_Empleado_Empleado`
    FOREIGN KEY (`Empleado_IDEmpleado`)
    REFERENCES `mydb`.`Empleado` (`IDEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `IDVenta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Cliente_IDCliente` INT NOT NULL,
  PRIMARY KEY (`IDVenta`),
  UNIQUE INDEX `IDVenta_UNIQUE` (`IDVenta` ASC),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_IDCliente` ASC),
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_IDCliente`)
    REFERENCES `mydb`.`Cliente` (`IDCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Folio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Folio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Folio` (
  `IDFolio` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `SubTotal` FLOAT NOT NULL,
  `Total` FLOAT NOT NULL,
  `Venta_IDVenta` INT NOT NULL,
  `Producto_IDProducto` INT NOT NULL,
  PRIMARY KEY (`IDFolio`, `Venta_IDVenta`, `Producto_IDProducto`),
  UNIQUE INDEX `IDFolio_UNIQUE` (`IDFolio` ASC),
  INDEX `fk_Folio_Venta1_idx` (`Venta_IDVenta` ASC),
  INDEX `fk_Folio_Producto1_idx` (`Producto_IDProducto` ASC),
  CONSTRAINT `fk_Folio_Venta1`
    FOREIGN KEY (`Venta_IDVenta`)
    REFERENCES `mydb`.`Venta` (`IDVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Folio_Producto1`
    FOREIGN KEY (`Producto_IDProducto`)
    REFERENCES `mydb`.`Producto` (`IDProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
